language: java
script: ./gradlew build
deploy:
  provider: releases
  api_key:
    secure: ozgAK9ONELypoUv2HzsMrJoPZLT2IYU3cNZKFifrjtlxVOdP5HW+lEjCbV3HitgbLc9ybHYmMYJB3wX369naJOUTK7wtKB15WP6DMFPuvLNZ5ubTpXWzhg3w4funWlFe4tf6d/+ZPtiqT1pkX0JnYhIF40xGCA5IwtuGbUtD+M2Y5LiddxMHemEd3KVTFzj3p5csxfUXgzZaUI9XEaBKl4DkPn42I0BBxymlwmirnHebo0yv+G6qZ1Xmq5LasTjkQvg3GC7Lmo6GrjSpcS6uIvqNyYrJ44kv+Pr6PRaNm39SmkpyoLAH1t9FJ11Efl9DjuzlrY4Fs5yQrYYU/b88/2sFK8w/BJTDQAmqFk0HZcky4Yot6CngtZwIVfAyyyRd2J9u7HK4E0PmgeJt9p8PNCLJM01boGQ/12u/GmbAH+qCzuB9viqem3I7Ap0dCRtV7/k6MGCoaFXy8ja+GQpcCu1LQIZmrJ2Ok1VkKhY2/bF6sf/9tSL305hRwX3AQRJASv1vWn8aOyX+lEX1HTutU0zRoB0cgeCK/0zxF6eHiWvwOnRr3d2tP5QbpXcteT6VrZSQSdFwEMKeEoNwHzO6/WvxHy1x5OCBoSev09Fbz9kloRV8ByteYGhm8f33ffHNYb8OPD41nIMA9bBfLLvyK0j1035hxaLAc+QB+Idx92g=
  file: build/libs/1018PowerUpJava.jar
  on:
    repo: firecrafty/1018PowerUpJava
    tags: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
